package com.aastu.model;

public enum Department {
  ARCHITECTURE,
  CIVIL_ENGINEERING,
  MINING_ENGINEERING,
  CHEMICAL_ENGINEERING,
  ENVIRNONMENTAL_ENGINEERING,
  ELECTROMECHANICAL_ENGINEERING,
  ELECTRICAL_AND_COMPUTER_ENGINEERING,
  MECHANICAL_ENGINEERING,
  SOFTWARE_ENGINEERING,

  BIOTECHNOLOGY_WITH_HONORS,
  GEOLOGY_WITH_HONORS,
  INDUSTRIAL_CHEMISTRY_WITH_HONORS,
  FOOD_SCIENCE_AND_APPLIED_NUTRITION
};
